/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package evm1;

import com.mysql.jdbc.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class party extends javax.swing.JInternalFrame {

    int party1,party2,party3,party4,party5,party6,party7,party8,party9,party10,party11,party12;
  /**
     * Creates new form party
     */
    public party() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("    SELECT PARTY");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/Parties1congress_0.png"))); // NOI18N
        jButton2.setText("INC");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pritam Singh");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/logo.jpg"))); // NOI18N
        jButton3.setText("AAP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/old_tv.jpg"))); // NOI18N
        jButton16.setText("Sukhmeet Singh");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/images.jpg"))); // NOI18N
        jButton17.setText("Harkirat Singh");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/LPG_Gas_cylinders.jpg"))); // NOI18N
        jButton15.setText("Arun Rampal");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Pritam Singh");

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/PVC-Water-Hand-Pump.jpg"))); // NOI18N
        jButton20.setText("Gurjeet singh");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/EC-allows-‘bolder’-lotus-symbol-of-the-BJP.jpg"))); // NOI18N
        jButton1.setText("BJP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Pardeep Singh");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/Flag_of_Samajwadi_Party.jpg"))); // NOI18N
        jButton7.setText("SP");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ashish Goyal");

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/scissorsphoto.jpg"))); // NOI18N
        jButton18.setText("Virat Sharma");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Harpal Singh");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Parveen Kumar");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm1/akali_dal.jpg"))); // NOI18N
        jButton4.setText("SAD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel8))
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party2";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        }

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party3";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        }
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party7";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party6";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party5";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        }
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party1";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
              voter_identity p1 =new voter_identity();
        p1.setVisible(true);
        this.getDesktopPane().add(p1);
        this.dispose();
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party8";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party9";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

        String votes=null;
        Connection con;
        Statement st,st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p="Party10";
            String Query = "select votes from totalvotes where partyno like '"+p+"' ";
             rs = st.executeQuery(Query);
            while(rs.next()) 
             {
              System.out.println(rs.getString(1));
               votes = rs.getString(1);
                System.out.println(votes);
             }
            votes= String.valueOf(Integer.parseInt(votes)+1);
             
             String Query1 = "update totalvotes set votes = '"+votes+"' where partyno like '"+p+"'";
             st1.executeUpdate(Query1);
              jButton1.setEnabled(false);
              jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton15.setEnabled(false);
             jButton16.setEnabled(false);
             jButton17.setEnabled(false);
             jButton7.setEnabled(false);
             jButton18.setEnabled(false);
             jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");
            
        }     catch (ClassNotFoundException | SQLException e) 
        {
            System.out.println(e);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
         String votes = null;
        Connection con;
        Statement st, st1;
        java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/evom", "root", "a");
            st = (Statement) con.createStatement();
            st1 = (Statement) con.createStatement();
            String p = "Party4";
            String Query = "select votes from totalvotes where partyno like '" + p + "' ";
            rs = st.executeQuery(Query);
            while (rs.next()) {
                System.out.println(rs.getString(1));
                votes = rs.getString(1);
                System.out.println(votes);
            }
            votes = String.valueOf(Integer.parseInt(votes) + 1);

            String Query1 = "update totalvotes set votes = '" + votes + "' where partyno like '" + p + "'";
            st1.executeUpdate(Query1);
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);
            jButton17.setEnabled(false);
            jButton7.setEnabled(false);
            jButton18.setEnabled(false);
            jButton20.setEnabled(false);
            JOptionPane.showMessageDialog(this, "THANK YOU FOR YOUR VOTE ");

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
